campagion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('tracker/', include('tracker.urls')),
    path('users/', include('users.urls')),
    path('management/', include('administration.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views
from . import js_views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
    path('campaign/new/', views.new_campaign, name="new_campaign"),
    path('campaign/<int:campaign_id>/', views.edit_campaign, name="edit_campaign"),
    path('client/new/', views.new_client, name="new_client"),
    path('client/<int:client_id>/', views.edit_client, name="edit_client"),
    path('clients/', views.clients, name="clients"),
    path('post/', views.post_handler, name="post_handler"),
    path('js/client/new/', views.bg_new_client, name="bg_new_client"),
    path('js/api_data/stats/campaign/', js_views.api_stats_campaign, name="api_data"),
    path('js/api_data/stats/minicampaign/', js_views.api_stats_minicampaign, name="api_data_mini"),
    path('js/api_data/sum/campaign/', js_views.api_sum_campaign, name="api_sum"),
    path('js/api_data/sum/minicampaign/', js_views.api_sum_minicampaign, name="api_sum_mini"),
    path('js/api_data/campaign/minicampaigns/', js_views.api_minicampaigns, name="api_get_minicampaigns")
]

tracker/urls.py
from django.urls import path
from django.shortcuts import reverse

from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.overview, name="overview"),
    path('<int:campaign_id>/', views.workflow, name="workflow"),
    path('milestones/', views.list_milestones, name="list_milestones"),
    path('milestones/new/', views.new_milestone, name="new_milestone"),
    path('milestones/<int:milestone_id>/', views.edit_milestone, name="edit_milestone"),
    path('<int:campaign_id>/design/', views.design_workflow, name="design_workflow"),
    path('templates/<int:template_id>/<int:campaign_id>/', views.edit_template, name="edit_template"),
    path('templates/choose/<int:campaign_id>/', views.choose_template, name="choose_template"),
    path('templates/new/<int:campaign_id>/', views.new_template, name="new_template"),
    path('uploads/new/<int:task_id>/', views.upload_file, name="upload_file"),

    #background-requests
    path('js/new_milestone/<int:campaign_id>', views.bg_new_milestone, name="bg_new_milestone")
]

def start_url():
    return reverse('tracker:overview')

tracker/forms.py
from django.forms import ModelForm, Form
import django.forms as forms
from tracker.models import Template, Task, Milestone

class TemplateForm(ModelForm):
    class Meta:
        model = Template
        fields = ['name']
        labels = {
            'name': 'Name'
        }

class UploadForm(ModelForm):
    class Meta:
        model = Task
        fields = ['uploaded_file']
        labels = {
            'uploaded_file': 'Datei'
        }

class MilestoneForm(ModelForm):
    def __init__(self, global_=False, *args, **kwargs):
        super(MilestoneForm, self).__init__(*args, **kwargs)
        if not global_:
            self.fields['for_campaign'] = forms.BooleanField(label="Nur für diese Kampagne", initial=True, required=False)
    
    class Meta:
        model = Milestone
        fields = ['name', 'duration', 'is_external', 'department', 'completer', 'upload_name']
        labels = {
            'duration': 'Dauer (d HH:MM:SS)',
            'is_external': 'Extern',
            'completer': 'Abschlussart',
            'upload_name': 'Dateibezeichnung (nur bei Upload)'
        }

    def save(self, campaign_id):
        try:
            if self.cleaned_data['for_campaign']:
                self.instance.campaign_id = campaign_id
        except:
            pass
        if self.cleaned_data['upload_name'] != None:
            self.instance.upload_dir = self.cleaned_data['upload_name'].lower() + "s"

        super().save()
        

tracker/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseForbidden
from django.urls import reverse
from django.db.models import Q
# Create your views here.
from tracker.models import Milestone, Task, Workflow, Node, Line, Template, Completer
from tracker.contrib.utils import handle_node_data
from tracker.forms import TemplateForm, UploadForm, MilestoneForm
from main.models import Client, Campaign
from users.models import Department
from datetime import datetime, timedelta
import json

def overview(request):
    if request.method == 'GET':
        if request.user.is_admin:
            context = {
                'active_tasks': Task.objects.active_tasks(),
                'campaigns': Campaign.objects.all().order_by('status')
            }
        else:
            context = {
                'active_tasks': Task.objects.get_from_user(request.user),
                'campaigns': sorted(set([a.campaign for a in request.user.assignee_set.all()]), key=lambda x: x.status)
            }
        return render(request, 'tracker/overview.html', context)
    else:
        if request.POST['action'] == 'REDIRECT':
            destination = request.POST['destination']
            if destination == 'WORKFLOW':
                return redirect('tracker:workflow', campaign_id=int(request.POST['campaign_id']))
            elif destination == 'EDIT_CAMPAIGN':
                return redirect('main:edit_campaign', campaign_id=int(request.POST['campaign_id']))
            elif destination == 'NEW_CAMPAIGN':
                return redirect('main:new_campaign')
        elif request.POST['action'] == 'FINISH_TASK':
            task = Task.objects.get(id=int(request.POST['task_id']))
            class_ = task.milestone.completer.handler_class()
            completer = class_(task, reverse('tracker:workflow', kwargs={'campaign_id': task.workflow.campaign.id}))
            return completer.handle()
        return redirect('tracker:overview')

def workflow(request, campaign_id):
    campaign = Campaign.objects.get(id=campaign_id)
    if request.method == 'POST':
        if request.POST['action'] == 'START_WORKFLOW':
            campaign.workflow.start(request)
            return redirect('tracker:workflow', campaign_id=campaign_id)
        elif request.POST['action'] == 'FINISH_TASK':
            task = Task.objects.get(id = int(request.POST['task_id']))
            if request.user != task.assigned_user():
                return HttpResponseForbidden()
            class_ = task.milestone.completer.handler_class()
            completer = class_(request, task, reverse('tracker:workflow', kwargs={'campaign_id': campaign_id}))
            return completer.handle()
        elif request.POST['action'] == 'RESET_TASK':
            task = Task.objects.get(id=int(request.POST['task_id']))
            if request.user != task.assigned_user():
                return HttpResponseForbidden()
            campaign.workflow.add_fallback_task(task)
            return redirect('tracker:workflow', campaign_id=campaign_id)
        elif request.POST['action'] == 'OPEN_DESIGN':
            return redirect('tracker:design_workflow', campaign_id=campaign_id)
        elif request.POST['action'] == 'CHOOSE_TEMPLATE':
            return redirect('tracker:choose_template', campaign_id=campaign_id)
        elif request.POST['action'] == 'EDIT_CAMPAIGN':
            return redirect('main:edit_campaign', campaign_id=campaign_id)
    client = campaign.client
    workflow = campaign.workflow
    workflow.calculate_tasks()
    start_date = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0) if not workflow.is_started() else workflow.start_date.replace(hour=0, minute=0, second=0, microsecond=0)
    context = {
        'client': client,
        'campaign': campaign,
        'workflow': campaign.workflow,
        'start_date': start_date.timestamp() * 1000,
        'end_date': workflow.last_relevant_date().timestamp() * 1000,
        'active_tasks': campaign.workflow.active_tasks(),
        'departments': json.dumps([{'id': d.id, 'name': d.name + " (" + d.get_assignee_name(campaign) + ")"} for d in Department.objects.all()])
    }
    return render(request, 'tracker/workflow.html', context)

def design_workflow(request, campaign_id):
    campaign = Campaign.objects.get(id=campaign_id)
    workflow = campaign.workflow

    if request.method == 'GET':
        context = {
            'campaign': campaign,
            'milestones': Milestone.objects.filter(Q(campaign__isnull=True) | Q(campaign=campaign), is_visible=True),
            'workflow': workflow,
            'form': MilestoneForm(),
            'completers': Completer.objects.all()
        }
        return render(request, 'tracker/design_workflow.html', context)

    handle_node_data(request.POST['data'], workflow)

    return redirect('tracker:workflow', campaign_id=campaign_id)

# TEMPLATES
def choose_template(request, campaign_id):
    if request.method == 'GET':
        return render(request, 'tracker/choose_template.html', {
            'campaign_id': campaign_id,
            'templates': Template.objects.all()
        })

    if request.POST['action'] == 'CHOSEN':
        campaign = Campaign.objects.get(id=campaign_id)
        workflow = campaign.workflow
        workflow.copy_nodes(Template.objects.get(id=request.POST['template_id']))
        return redirect('tracker:workflow', campaign_id=campaign_id)
    elif request.POST['action'] == 'EDIT':
        return redirect('tracker:edit_template', template_id=int(request.POST['template_id']), campaign_id=campaign_id)
    elif request.POST['action'] == 'DELETE':
        t = Template.objects.get(id=int(request.POST['template_id']))
        t.delete()
        return redirect('tracker:choose_template', campaign_id=campaign_id)
    elif request.POST['action'] == 'NEW_TEMPLATE':
        return redirect('tracker:new_template', campaign_id=campaign_id)
    elif request.POST['action'] == 'ABORT':
        return redirect('tracker:workflow', campaign_id=campaign_id)

def edit_template(request, template_id, campaign_id):
    template = Template.objects.get(id=template_id)
    if request.method == 'GET':
        context = {
            'template': template,
            'milestones': Milestone.objects.all(),
            'use_template': True,
            'form': MilestoneForm(global_=True),
            'campaign_id': campaign_id
        }
        return render(request, 'tracker/design_workflow.html', context)

    handle_node_data(request.POST['data'], template)

    return redirect('tracker:choose_template', campaign_id=campaign_id) # Hier irgendwie zum Choose Template zurück

def new_template(request, campaign_id):
    if request.method == 'POST':
        form = TemplateForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('tracker:edit_template', template_id=form.instance.id, campaign_id=campaign_id)
    else:
        form = TemplateForm()
    context = {
        'class_name': 'Vorlage',
        'form': form,
        'new': True,
        'url': reverse('tracker:new_template', kwargs={'campaign_id': campaign_id})
    }
    return render(request, 'main/simple_form.html', context)
# END TEMPLATES

def list_milestones(request):
    context = {
        'milestones': Milestone.objects.filter(campaign__isnull=True, is_visible=True)
    }
    return render(request, 'tracker/list_milestones.html', context)

def new_milestone(request):
    if request.method == 'POST':
        form = MilestoneForm(False, request.POST)
        if form.is_valid():
            form.save(None)
            return redirect('tracker:list_milestones')
    else:
        form = MilestoneForm()
    context = {
        'form': form,
        'new': True,
        'class_name': 'Meilenstein',
        'url': reverse('tracker:new_milestone')
    }
    return render(request, 'main/simple_form.html', context)

def edit_milestone(request, milestone_id):
    milestone = Milestone.objects.get(id=milestone_id)
    if request.method == 'POST':
        if request.POST['action'] == 'DELETE':
            milestone.is_visible = False
            milestone.save()
            return redirect('tracker:list_milestones')
        form = MilestoneForm(False, request.POST, instance=milestone)
        if form.is_valid():
            form.save(None)
            return redirect('tracker:list_milestones')
    else:
        form = MilestoneForm(instance=milestone, global_=True)
    context = {
        'form': form,
        'new': False,
        'class_name': 'Meilenstein',
        'url': reverse('tracker:edit_milestone', kwargs={'milestone_id': milestone_id}),
        'deletable': True
    }
    return render(request, 'main/simple_form.html', context)

def upload_file(request, task_id):
    task = Task.objects.get(id=task_id)
    if task.milestone.completer.name != "UploadCompleter":
        raise TypeError("Task hat keinen UploadCompleter")
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES, instance=task)
        if form.is_valid():
            form.save()
            class_ = task.milestone.completer.handler_class()
            completer = class_(request, task, None)
            completer.complete()
            return redirect('tracker:workflow', campaign_id=task.workflow.campaign.id)
    else:
        form = UploadForm(instance=task)
    return render(request, 'main/simple_form.html', {
        'class_name': task.milestone.upload_name + " hochladen",
        'form': form,
        'new': True,
        'url': reverse('tracker:upload_file', kwargs={'task_id': task_id}),
        'with_uploads': True
    })


#BACKGROUND
def bg_new_milestone(request, campaign_id):
    if request.method == "GET":
        raise ValueError("This view should never be accessed via GET")
    form = MilestoneForm(campaign_id == 0, request.POST)
    if form.is_valid():
        form.save(campaign_id)

tracker/templates/tracker/choose_template.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Vorlage auswählen{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'tracker/css/choose_template.css' %}">
<script type="text/javascript" src="{% static 'tracker/js/choose_template.js' %}"></script>
{% endblock %}

{% block content %}
<div id="main_container">
  <div class="title">Vorlage auswählen</div>
  <div id="template_container">
    {% for template in templates %}
      <div class="template" data-template_id="{{ template.id }}">
        <div class="text">
          {{ template.name }}
        </div>
        <img src="{% static 'tracker/images/settings_icon.png' %}" class="edit_icon">
        <img src="{% static 'tracker/images/delete_icon.png' %}" class="delete_icon">
      </div>
    {% endfor %}
  </div>
  <div id="button_container">
    <div class="button" id="btn_new_template">Neue Vorlage</div>
    <div class="button" id="btn_abort">Abbrechen</div>
  </div>
</div>
{% endblock %}


{% block forms %}
  <form action="{{ url }}" method="post" id="post_form" hidden>
    {% csrf_token %}
    <input type="text" name="action" id="input_action">
    <input type="text" name="template_id" id="input_template_id">
  </form>
{% endblock %}

tracker/templates/tracker/design_workflow.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Workflow Design{% endblock %}

{% block head %}
  <script type="text/javascript">
    {% if use_template %}
      const NODES = {{ template.get_nodes|safe }};
    {% else %}
      const NODES = {{ workflow.get_nodes|safe }};
    {% endif %}
  </script>
  <script type="text/javascript" src="{% static 'tracker/js/design_workflow/bezier.js' %}"></script>
  <script type="text/javascript" src="{% static 'tracker/js/design_workflow/milestone.js' %}"></script>
  <script type="text/javascript" src="{% static 'tracker/js/design_workflow/design_workflow.js' %}"></script>
  <link rel="stylesheet" href="{% static 'tracker/css/design_workflow.css' %}">
{% endblock %}

{% block content %}
  <div id="main_container">
    <div class="title">
      {% if use_template %}Template{% else %}Workflow{% endif %} designen
    </div>
    <div id="content_container">
      <div id="node_container">
        <svg id="svg" xmlns="http://www.w3.org/2000/svg">
        </svg>
      </div>
      <div id="milestone_container">
        {% for milestone in milestones %}
          {{ milestone.to_html|safe }}
        {% endfor %}
      </div>
    </div>
    <div id="button_container">
      <div class="button" id="btn_save">
        Speichern
      </div>
      <div class="button" id="btn_add_task">
        Task hinzufügen
      </div>
    </div>
  </div>
  <div hidden>
    <div class="milestone noselect" id="milestone_js_template">
      <div class="milestone_name"></div>
      <div class="milestone_duration"></div>
      <div class="milestone_department"></div>
      <span class="dot left"></span>
      <span class="dot right"></span>
      <span class="dot bottom"></span>
    </div>
  </div>
  <div id="hidden_div" hidden></div>{# wird im javascript abused #}
{% endblock %}

{% block forms %}
<form action="{% if use_template %}{% url 'tracker:edit_template' template.id campaign_id %}{% else %}{% url 'tracker:design_workflow' campaign.id %}{% endif %}" method="post" id="data_form" hidden>
  {% csrf_token %}
  <input type="text" name="data" id="form_data_input">
</form>
{% endblock %}

{% block popup_title %}
  Neuen Task erstellen
{% endblock %}

{% block popup_content %}
  <form action="{% url 'tracker:bg_new_milestone' campaign.id|default:0 %}" id="new_milestone_form" method="POST">
    <table id="new_milestone_table">
        {{ form.as_table }}
    </table>
    {% csrf_token %}
  </form>
  
  <div class="button" onclick="submit_milestone_form();">
    Erstellen
  </div>
{% endblock %}

tracker/templates/tracker/list_milestones.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Meilensteine{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'tracker/css/list_milestones.css' %}">
{% endblock %}

{% block content %}
    <div class="title">Meilensteine<a href="{% url 'tracker:new_milestone' %}"><img src="{% static 'tracker/images/new_icon.png' %}" id="new_milestone"></a></div>
    <div id="milestone_container">
        {% for milestone in milestones %}
            <div class="milestone">
                <a href="{% url 'tracker:edit_milestone' milestone.id %}">
                    <div class="milestone_title">{{ milestone.name }}</div>
                    <div class="milestone_data">{% if milestone.is_external %}Extern{% else %}{{ milestone.hours }}h{% endif %}</div>
                    <div class="milestone_data">{{ milestone.department }}</div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

tracker/templates/tracker/overview.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Overview{% endblock %}
{% block head %}
   <link rel="stylesheet" href="{% static 'tracker/css/overview.css' %}">
   <script type="text/javascript" src="{% static 'tracker/js/overview.js' %}"></script>
{% endblock %}

{% block content %}
  <div id="main_container">
    <div class="title" style="grid-area: task_title;">
      Bald fällige Aufgaben
    </div>
    <div id="task_container">
      {% for task in active_tasks %}
        <a href="{% url 'tracker:workflow' task.workflow.campaign.id %}">
          <div class="task_container{% if task.assigned_user == user %} own{% endif %}" data-task_id="{{ task.id }}">
            <div class="task_client">
              {{ task.workflow.campaign.name }}
            </div>
            <div class="task_due_date">
              {{ task.due_date_string }}
            </div>
            <div class="task_name">
              {{ task.milestone.name }}
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
    <div class="title" style="grid-area: campaign_title">
      Aktive Kampagnen
    </div>
    <div id="active_campaign_container">
      {% for campaign in campaigns %}
        {% if campaign.is_active %}
          <div class="active_campaign" data-campaign_id="{{ campaign.id }}">
            <div class="campaign_client">
              {{ campaign.client.name }}
            </div>
            <div class="campaign_name">
              {{ campaign.name }}
            </div>
            <div class="campaign_runtime">
              {{ campaign.date_string }}
            </div>
            <div class="campaign_budget">
              € {{ campaign.budget_left|floatformat:2 }}
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
    <div id="client_title">
      <div class="title" style="grid-column: 2">
        Kampagnen-Übersicht
      </div>
      <img src="{% static 'tracker/images/new_icon.png' %}" id="new_icon"> 
    </div>
    
    
    <div id="campaign_container">
      {% for campaign in campaigns %}
        <div class="campaign" data-campaign_id="{{ campaign.id }}">
          <div class="title">{{ campaign.name }}</div>
          <div class="badge" style="background-color:{{ campaign.status_color }}"></div>
          <div class="text small">{{ campaign.client.name }}</div>
          <div class="hard_sep"></div>
          <div class="text">{{ campaign.date_string }}</div>
          {% if not campaign.is_active %}
            <div class="text">Dauer: {{ campaign.days }} Tage</div>
          {% endif %}
          <div class="sep"></div>
          <div class="text">Gesamtbudget: {{ campaign.budget }}€</div>
          <div class="text">Restbudget: {{ campaign.budget_left|floatformat:2 }}€</div>
          <div class="footer">
            <a href="{% url 'main:edit_campaign' campaign.id %}"><div class="data footer_option">Daten</div></a>
            <a href="{% url 'tracker:workflow' campaign.id %}"><div class="workflow footer_option">Workflow</div></a>
          </div>
          {% if not campaign.workflow.is_finished %}
            <div class="status">
              {% for task in campaign.workflow.active_tasks %}
                <div class="status_text">
                  {{ task.milestone.name }}{% if task.milestone.is_external %}(E){% endif %}
                </div>
              {% endfor %}
            </div>
          {% endif %}
        </div>
      {% empty %}
        Keine Kampagnen gefunden
      {% endfor %}
    </div>
  </div>
{% endblock content %}

{% block forms %}
  <form action="{% url 'tracker:overview' %}" method="post" hidden id="form">
    {% csrf_token %}
    <input type="text" name="action" id="input_action">
    <input type="text" name="destination" id="input_destination">
    <input type="text" name="campaign_id" id="input_campaign_id">
    <input type="text" name="client_id" id="input_client_id">
    <input type="text" name="task_id" id="input_task_id">
  </form>
{% endblock %}

tracker/templates/tracker/workflow.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Workflow bearbeiten{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{% static 'tracker/css/workflow.css' %}">
  <script type="text/javascript" src="{% static 'tracker/js/workflow/canvas.js' %}"></script>
  <script type="text/javascript" src="{% static 'tracker/js/workflow/milestone_container.js' %}"></script>
  <script type="text/javascript">
    const VALUES = {
      'workflow': {{ workflow.to_json|safe }},
      'tasks': {{ workflow.tasks_to_json|safe }},
      'start_date': new Date({{ start_date }}),
      'end_date': new Date({{ end_date }}),
      'departments': {{ departments|safe }}
    };
  </script>
  <script type="text/javascript" src="{% static 'tracker/js/workflow/workflow.js' %}"></script>
{% endblock %}

{% block content %}
  <div id="main_container">
    <div id="client_container">
      <div id="client_name" class="name">
        {{ client.name }}
      </div>
      <div id="campaign_name" class="name">
        {{ campaign.name }}
      </div>
      <div class="name">
        {{ campaign.runtime_string }}
      </div>
      <div>
        <div class="button noselect" id="btn_edit_campaign" onclick="edit_campaign()">
          Kampagne bearbeiten
        </div>
      </div>
      {# Hier gibt es dann noch allgemeine Infos zum Kunden und zur Kampagne #}
    </div>
    <div class="workflow_title" style="grid-area: workflow_title">
      Aktiver Workflow
    </div>
    <img src="{% static 'tracker/images/settings_icon.png' %}" id="settings" onclick="open_design()">
    {% if not workflow.is_started %}
      <img src="{% static 'tracker/images/open_folder.png' %}" id="open_folder" onclick="open_template()">
    {% endif %}
    <div id="workflow_container">
      <canvas id="workflow_date_canvas" class="date_canvas" width="800px" height="50px"></canvas>
      <canvas id="workflow_canvas" class="timeline_canvas" height="360px"></canvas>
    </div>
    {% if workflow.is_started %}
      <div class="workflow_title" style="grid-area: task_title">
      Aktive Aufgabe
    </div>
    <div class="button_container" style="grid-area: btn_edit_milestone">
      <a href="{% url 'tracker:list_milestones' %}">
        <div class="button" id="btn_edit_milestones">
          Meilensteine bearbeiten
        </div>
      </a>
    </div>
    <div id="active_task_container">
      {% for task in active_tasks %}
      <div class="active_task_container">
        <div class="active_task_text" style="grid-area: name;">
          {{ task.milestone.name }} ({{ task.assigned_user }})
        </div>
        <div class="active_task_text" style="grid-area: date">
          {{ task.due_date_string }}
        </div>
        <div id="active_task_button_container">
          {% if task.fallback_task is not None %}
            <div class="button active_task_button noselect{% if task.assigned_user != user and not user.is_admin %} disabled{% endif %}" data-task_id="{{ task.id }}" data-action="reset">Zurücksetzen</div>
          {% endif %}
          <div class="button active_task_button noselect{% if task.assigned_user != user and not user.is_admin %} disabled{% endif %}" data-task_id="{{ task.id }}" data-action="finish">Abschließen</div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
      <div class="button_container" style="grid-area: task_title">
        <button type="button" name="button" onclick="btn_start_workflow_click()">Workflow starten</button>
      </div>
    {% endif %}
  </div>
{% endblock %}


{% block forms %}
  <form action="{% url 'tracker:workflow' campaign.id %}" method="post" hidden id="post_form">
    <input type="text" name="action" id="post_form_action"> {# START_WORKFLOW, FINISH_TASK, OPEN_DESIGN, EDIT_CAMPAIGN #}
    <input type="text" name="task_id" id="post_form_task_id">
    {% csrf_token %}
  </form>
{% endblock %}