campagion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('tracker/', include('tracker.urls')),
    path('users/', include('users.urls')),
    path('management/', include('administration.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views
from . import js_views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
    path('campaign/new/', views.new_campaign, name="new_campaign"),
    path('campaign/<int:campaign_id>/', views.edit_campaign, name="edit_campaign"),
    path('client/new/', views.new_client, name="new_client"),
    path('client/<int:client_id>/', views.edit_client, name="edit_client"),
    path('clients/', views.clients, name="clients"),
    path('post/', views.post_handler, name="post_handler"),
    path('js/client/new/', views.bg_new_client, name="bg_new_client"),
    path('js/api_data/stats/campaign/', js_views.api_stats_campaign, name="api_data"),
    path('js/api_data/stats/minicampaign/', js_views.api_stats_minicampaign, name="api_data_mini"),
    path('js/api_data/sum/campaign/', js_views.api_sum_campaign, name="api_sum"),
    path('js/api_data/sum/minicampaign/', js_views.api_sum_minicampaign, name="api_sum_mini"),
    path('js/api_data/campaign/minicampaigns/', js_views.api_minicampaigns, name="api_get_minicampaigns")
]

users/urls.py
from django.urls import path
from django.shortcuts import reverse

from . import views

app_name="users"

urlpatterns = [
    path('', views.overview, name="overview"),
    path('login/', views.login, name="login"),
    path('edit/<int:user_id>/', views.edit_user, name="edit_user"),
    path('department/<int:department_id>/', views.edit_department, name="edit_department"),
    path('department/new/', views.new_department, name="new_department"),
    path('register/<str:key>/', views.register, name="register"),
]

users/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from main.models import Assignee
import uuid

# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=40)
    color = models.CharField(max_length=10, default="#717171")

    def __str__(self):
        return self.name

    def get_assignee_name(self, campaign):
        try:
            return Assignee.objects.get(department=self, campaign=campaign).user.name()
        except Assignee.DoesNotExist:
            return None

class PermissionGroup(models.Model):
    name = models.CharField(max_length=80)
    codename = models.CharField(max_length=40)

    def __str__(self):
        return self.name
    
class Invitation(models.Model):
    invitor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="invitations")
    email = models.EmailField()
    key = models.UUIDField(default=uuid.uuid4, editable=False)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    group = models.ForeignKey(PermissionGroup, on_delete=models.SET_NULL, null=True)
    
    def link(self):
        return settings.HOST_NAME + reverse('users:register', kwargs={'key': self.key})

users/forms.py
from django import forms
from django.contrib.auth import authenticate as dj_authenticate
from django.contrib.auth import login
from users.models import Department, PermissionGroup, Invitation
from users.mails import send_invitation_mail
from main.models import User
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, label="E-Mail")
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)

    def authenticate(self, request):
        return dj_authenticate(request, username=self.cleaned_data['username'], password=self.cleaned_data['password'])

class RegistrationForm(forms.Form):
    first_name = forms.CharField(label="Vorname:", max_length=70)
    last_name = forms.CharField(label="Nachname:", max_length=80)
    email = forms.EmailField(label="E-Mail:")
    password1 = forms.CharField(widget=forms.PasswordInput(), label="Passwort:")
    password2 = forms.CharField(widget=forms.PasswordInput(), label="Password wiederholen:")

    def clean(self):
        cleaned_data = super().clean()

        if cleaned_data.get('password1') != cleaned_data.get('password2'):
            raise ValidationError("Die Passwörter stimmen nicht überein!")
            
        password = cleaned_data.get('password1')
        validate_password(password) #raises a ValidationError if the password is not secure enough

        email = self.cleaned_data['email']

        if len(User.objects.filter(email=email)) != 0:
            self.add_error("email", "Es existiert bereits ein User mit dieser E-Mail Adresse")

    def create_user(self, request, invitation):
        user = User.objects.create_user(
            username=self.cleaned_data['email'],
            password=self.cleaned_data['password1'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            group=invitation.group,
            email=self.cleaned_data['email']
        )
        login(request, user)

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name']

def group_choices():
    try:
        return [(group.id, group.name) for group in PermissionGroup.objects.all()]
    except: return []

class InvitationForm(forms.Form):
    email = forms.EmailField(label="Bitte hier die E-Mail Adresse der einzuladenden Person eingeben")
    group = forms.IntegerField(
        label="Welcher Benutzergruppe soll dieser User angehören?",
        widget=forms.Select(choices=group_choices()),
    )

    def clean(self):
        email = self.cleaned_data['email']

        if User.objects.filter(email=email).count() != 0:
            self.add_error("email", "Es existiert bereits ein User mit dieser E-Mail Adresse!")

    def invite(self, invitor):
        invitation = Invitation(invitor=invitor, email=self.cleaned_data['email'], group=PermissionGroup.objects.get(id=self.cleaned_data['group']))
        invitation.save()
        send_invitation_mail(invitation)

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'group', 'profile_picture']
        
    def render(self):
        html = ""
        for field in self.fields.keys():
            hidden = field == 'profile_picture' 
            html += f"""<tr {"hidden" if hidden else ""}>
                        {self[field].errors}
                        <td><label for="{self[field].id_for_label}">{self[field].label}:</label></td>
                        <td>{self[field]}</td>
                    </tr>"""
        return html

users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login as login_user
from users.forms import LoginForm
from main.models import User
from users.models import Department, Invitation
from users.forms import DepartmentForm, InvitationForm, RegistrationForm, EditUserForm
from django.contrib import messages

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.authenticate(request)
            if user is not None:
                login_user(request, user)
                return redirect('main:index')
    else:
        form = LoginForm()
    context = {
        'form': form
    }
    return render(request, 'users/login.html', context)

def register(request, key):
    invitation = Invitation.objects.get(key=key)
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.create_user(request, invitation)
            return redirect('main:index')
    else:
        form = RegistrationForm(initial={'email': invitation.email})

    context = {
        'class_name': 'Registrierung',
        'form': form,
        'new': True,
        'url': reverse('users:register', kwargs={'key': key})
    }
    return render(request, 'main/simple_form.html', context)

def overview(request):
    if request.method == 'POST':
        action = request.POST['action']
        if action == 'EDIT_USER':
            user_id = int(request.POST['user_id'])
            return redirect('users:edit_user', user_id=user_id)
        if action == 'EDIT_DEPARTMENT':
            department_id = int(request.POST['department_id'])
            return redirect('users:edit_department', department_id=department_id)
        if action == 'NEW_USER':
            form = InvitationForm(request.POST)
            if form.is_valid():
                form.invite(request.user)
                messages.success(request, "Der User wurde erfolgreich eingeladen!")
                return redirect('users:overview')
            context = {
                'users': User.objects.filter(is_active=True),
                'departments': Department.objects.all(),
                'invitation_form': form,
                'edit_invitation_form': True
            }
        if action == 'NEW_DEPARTMENT':
            return redirect('users:new_department')
    else:
        context = {
            'users': User.objects.filter(is_active=True),
            'departments': Department.objects.all(),
            'invitation_form': InvitationForm()
        }
    return render(request, 'users/overview.html', context)


# Edit User und Department
def edit_user(request, user_id):
    user = User.objects.get(id=user_id)
    if request.method == 'GET':
        form = EditUserForm(instance=user)
    else:
        print(request.POST)
        print(request.FILES)
        form = EditUserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'User wurde erfolgreich gespeichert!')
            return redirect('users:overview')
    context = {
        'edit_user': user,
        'form': form
    }
    return render(request, 'users/edit_user.html', context)

def edit_department(request, department_id):
    department = Department.objects.get(id=department_id)
    if request.method == 'POST':
        form = DepartmentForm(request.POST, instance=department)

        if form.is_valid():
            form.save()
            return redirect('users:overview')
    else:
        form = DepartmentForm(instance=department)

    context = {
        'class_name': "Department",
        'form': form,
        'url': reverse('users:edit_department', kwargs={'department_id': department_id})
    }
    return render(request, 'main/simple_form.html', context)

def new_department(request):
    if request.method == 'POST':
        form = DepartmentForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('users:overview')
    else:
        form = DepartmentForm()

    context = {
        'class_name': "Department",
        'form': form,
        'new': True,
        'url': reverse('users:new_department')
    }
    return render(request, 'main/simple_form.html', context)

users/templates/users/edit_user.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}User bearbeiten{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'users/css/edit_user.css' %}">
    <script src="{% static 'users/js/edit_user.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="main_container">
        <div id="img_container">
            <img id="profile_picture_img" src="{% if not user.profile_picture %}{% static 'users/images/user.png' %}{% else %}{{ user.profile_picture.url }}{% endif %}">
        </div>
        <div class="title">
            {{ edit_user.name }}
        </div>
        <div style="grid-area: upload;">
            <div class="button noselect" id="upload_button">
                Bild hochladen
            </div>
        </div>
        <div id="form_container">
            <form action="{% url 'users:edit_user' edit_user.id %}" method="POST" enctype="multipart/form-data" id="user_form">
                {% csrf_token %}
                <table>
                    {{ form.render|safe }}
                </table>
            </form>
        </div>
    </div>
    <div id="button_container">
        <div class="button noselect" id="save_button">
            Speichern
        </div>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block title %}CAMPAGION - LOGIN{% endblock %}

{% block head %}
<style media="screen">
  table {
    margin: 0px auto;
    margin-top: 40px;
  }
  table label {
    font-weight: normal;
  }
  table th {
    text-align: right;
  }
  .title {
    text-align: center;
    height: 40px;
    font-size: 30px;
    line-height: 30px;
    margin: 20px;
  }
</style>
{% endblock %}

{% block content %}
<div class="title">
  Login
</div>
<form action="{{ url }}" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <div style="text-align: center; margin: 10px;">
    <input type="submit" value="Login">
  </div>
</form>
{% endblock %}

users/templates/users/overview.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}User-Management{% endblock %}

{% block head %}
    <script>
        const VALUES = {
            'EDIT_INVITATION_FORM': {% if edit_invitation_form %}true{% else %}false{% endif %}
        };
    </script>
    <link rel="stylesheet" href="{% static 'users/css/overview.css' %}">
    <script src="{% static 'users/js/overview.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="main_container">
        <div class="title" style="grid-area: title">User-Management</div>
        <div id="content_container">
            <div id="department_container">
                {% for department in departments %}
                    <div class="department" data-department_id="{{ department.id }}">
                        {{ department.name }}
                    </div>
                {% endfor %}
            </div>
            <div id="user_container">
                {% for user in users %}
                    <div class="user" data-user_id="{{ user.id }}">
                        <div class="user_profile_picture">
                            <img src="{% if not user.profile_picture %}{% static 'users/images/user.png' %}{% else %}{{ user.profile_picture.url }}{% endif %}">
                        </div>
                        <div class="user_name">{{ user.name }}</div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div id="button_container">
            <div class="button" id="btn_new_department">Neues Department</div>
            <div class="button" id="btn_new_user">Neuer User</div>
        </div>
    </div>
{% endblock %}

{% block forms %}
    <form action="{% url 'users:overview' %}" method="POST" id="action_form">
        {% csrf_token %}
        <input type="text" name="action" id="input_action">
        <input type="text" name="department_id" id="input_department_id">
        <input type="text" name="user_id" id="input_user_id">
    </form>
{% endblock %}

{% block popup_title %}Neuen User einladen{% endblock %}

{% block popup_content %}
    <form action="{% url 'users:overview' %}" method="POST" id="invitation_form">
        <div class="field_wrapper">
            {{ invitation_form.email.errors }}
            <label for="id_email">{{ invitation_form.email.label }}:</label><br>
            {{ invitation_form.email }}
        </div>
        <div class="field_wrapper">
            {{ invitation_form.group.errors }}
            <label for="id_group">{{ invitation_form.group.label }}:</label><br>
            {{ invitation_form.group }}
        </div>
        {% csrf_token %}
        <input type="text" name="action" value="NEW_USER" readonly hidden>
    </form>
    <div class="button" onclick="invite_user()">Absenden</div>
{% endblock %}