campagion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('tracker/', include('tracker.urls')),
    path('users/', include('users.urls')),
    path('management/', include('administration.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views
from . import js_views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
    path('campaign/new/', views.new_campaign, name="new_campaign"),
    path('campaign/<int:campaign_id>/', views.edit_campaign, name="edit_campaign"),
    path('client/new/', views.new_client, name="new_client"),
    path('client/<int:client_id>/', views.edit_client, name="edit_client"),
    path('clients/', views.clients, name="clients"),
    path('post/', views.post_handler, name="post_handler"),
    path('js/client/new/', views.bg_new_client, name="bg_new_client"),
    path('js/api_data/stats/campaign/', js_views.api_stats_campaign, name="api_data"),
    path('js/api_data/stats/minicampaign/', js_views.api_stats_minicampaign, name="api_data_mini"),
    path('js/api_data/sum/campaign/', js_views.api_sum_campaign, name="api_sum"),
    path('js/api_data/sum/minicampaign/', js_views.api_sum_minicampaign, name="api_sum_mini"),
    path('js/api_data/campaign/minicampaigns/', js_views.api_minicampaigns, name="api_get_minicampaigns")
]

tracker/urls.py
from django.urls import path
from django.shortcuts import reverse

from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.overview, name="overview"),
    path('<int:campaign_id>/', views.workflow, name="workflow"),
    path('milestones/', views.list_milestones, name="list_milestones"),
    path('milestones/new/', views.new_milestone, name="new_milestone"),
    path('milestones/<int:milestone_id>/', views.edit_milestone, name="edit_milestone"),
    path('<int:campaign_id>/design/', views.design_workflow, name="design_workflow"),
    path('templates/<int:template_id>/<int:campaign_id>/', views.edit_template, name="edit_template"),
    path('templates/choose/<int:campaign_id>/', views.choose_template, name="choose_template"),
    path('templates/new/<int:campaign_id>/', views.new_template, name="new_template"),
    path('uploads/new/<int:task_id>/', views.upload_file, name="upload_file"),

    #background-requests
    path('js/new_milestone/<int:campaign_id>', views.bg_new_milestone, name="bg_new_milestone")
]

def start_url():
    return reverse('tracker:overview')

main/forms.py
from django import forms
from django.db.models import Sum, Avg
from django.contrib.auth import authenticate as dj_authenticate
from django.core.exceptions import ValidationError
from django.contrib.staticfiles.storage import staticfiles_storage

from .models import Client, Campaign, MiniCampaign
from .api_models import CampaignStats
from users.models import Department
from main.models import User, Assignee
from main.contrib.widgets import DatePickerWidget

class CampaignForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CampaignForm, self).__init__(*args, **kwargs)
        self.fields['client'] = forms.ModelChoiceField(Client.objects.order_by("name"), required=True, label="Kunde")
        self.fields['children_json'] = forms.JSONField(widget=forms.HiddenInput())
        self.addons = {
            'client': f"<div class='form_addon'><img src='{staticfiles_storage.url('main/images/plus.png')}' id='add_client'></img></div>",
        }

        for department in Department.objects.all():
            try:
                assignee = Assignee.objects.get(campaign=self.instance, department=department)
            except Assignee.DoesNotExist:
                assignee = None

            self.fields[f'assignee_{department.id}'] = forms.IntegerField(
                label=f"Verantwortlich für {department.name}",
                widget=forms.Select(choices=[(-1, "----------------")] + [(user.id, user.name()) for user in User.objects.all()])
            )
            if assignee != None:
                self.fields[f'assignee_{department.id}'].initial = assignee.user.id


    def clean(self):
        self.assignee_datas = [(int(data[0].split('_')[-1]), data[1]) for data in self.cleaned_data.items() if 'assignee' in data[0]]
        
        for data in self.assignee_datas:
            if data[1] == -1:
                raise ValidationError("Zu jedem Department muss ein User ausgewählt sein!")

    def save(self):
        super(CampaignForm, self).save()

        for data in self.assignee_datas:
            department = Department.objects.get(id=data[0])
            user = User.objects.get(id=data[1])

            try:
                assignee = Assignee.objects.get(department=department, user=user, campaign=self.instance)
            except Assignee.DoesNotExist:
                previous = Assignee.objects.filter(campaign=self.instance, department=department)
                if len(previous) == 1: #Wenn es schon eine Assignte Person gibt
                    previous[0].user = user
                    previous[0].save()
                else:
                    assignee = Assignee(department=department, user=user, campaign=self.instance)
                    assignee.save()

        ids = [c.id for c in self.instance.children_set.all()]
        for row in self.cleaned_data['children_json']['rows']:
            print(row)
            if row['id'] is not None:
                c = MiniCampaign.objects.get(id=row['id'])
                ids.remove(row['id'])
            else:
                c = MiniCampaign(campaign=self.instance)
            c.name = row['name']
            c.api_id = row['api_id']
            c.save()
        
        MiniCampaign.objects.filter(id__in=ids).delete()

    class Meta:
        model = Campaign
        fields = ['name', 'client', 'budget', 'fee_percentage', 'campagion_budget', 'planned_start_date', 'days']
        labels = {
            'name': 'Name',
            'client': 'Kunde',
            'planned_start_date': 'Geplantes Startdatum',
            'days': 'Dauer (in Tagen)',
            'budget': 'Werbebudget',
            'campagion_budget': 'Paketpreis',
            'fee_percentage': 'Abgabe in %'
        }
        widgets = {
            'planned_start_date': DatePickerWidget()
        }
    #Diese Render method wäre nice auf allen Forms zu haben :(
    def render(self):
        html = ""
        for field in self.fields.keys():
            hidden = isinstance(self.fields[field].widget, forms.HiddenInput)
            try:
                addon = self.addons[field]
            except:
                addon = ""

            if hidden:
                html += self[field].__str__()
            else:
                html += f"""<div class="field_wrapper">
                            {self[field].errors}
                            <label for="{self[field].id_for_label}">{self[field].label}:</label>
                            <div class="widget_wrapper">
                                {self[field]}
                                {addon}
                            </div>
                        </div>"""
        return html

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'contact_name', 'phone', 'email']
        labels = {
            'name': 'Name',
            'contact_name': 'Name der Kontaktperson',
            'phone': 'Telefonnummer',
            'email': 'E-Mail Adresse'
        }

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)

    def authenticate(self, request):
        return dj_authenticate(request, username=self.cleaned_data['username'], password=self.cleaned_data['password'])

class CampaignDataForm(forms.Form):
    impressions = forms.CharField(max_length=200, label="Impressions")
    revenue = forms.CharField(max_length=200, label="Ausgaben (in €)")
    clicks = forms.CharField(max_length=200, label="Clicks")
    ctr = forms.CharField(max_length=200, label="CTR")
    ecpm = forms.CharField(max_length=200, label="eCPM")
    ecpc = forms.CharField(max_length=200, label="eCPC")
    conversions = forms.CharField(max_length=200, label="Conversions")

    def __init__(self, campaign, *args, **kwargs):
        super().__init__(*args, **kwargs)

        minicampaigns = campaign.children_set.all()
        stats = {}

        for minicampaign in minicampaigns:
            result = minicampaign.stats_set.all().aggregate(
                        impressions=Sum('impressions'), 
                        revenue=Sum('revenue'), 
                        clicks=Sum('clicks'),
                        conversions=Sum('conversions')
                    )
            if len(stats.keys()) == 0:
                stats = result
            else:
                for k, v in result.items():
                    stats[k] += v
        
        for key in self.fields.keys():
            self.fields[key].widget.attrs['readonly'] = True
            self.fields[key].initial = round(stats[key], 4)

main/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth import login as login_user
from django.contrib.auth import logout
from django.contrib import messages
from django.conf import settings
from django.views.decorators.clickjacking import xframe_options_sameorigin

from .models import Campaign, Client, User
from users.models import Department
from campagion.contrib.utils import ModuleManager
from tracker.models import Workflow
from main.forms import ClientForm
from .forms import CampaignForm, LoginForm, ClientForm, CampaignDataForm
from django.contrib import messages

from datetime import date, datetime, timedelta
# Create your views here.

def index(request):
    if request.method == 'GET':
        request.session['active_module'] = None
        module_manager = ModuleManager()
        context = {
            'modules': module_manager.get_modules(request, [
                'dashboard',
                'clients',
                'users',
                'commissions'
            ])
        }
        return render(request, 'main/index.html', context)
    else:
        if request.POST['action'] == 'REDIRECT':
            m = Module(request.POST['module'])
            request.session['active_module'] = request.POST['module']
            return redirect(m.home_view)

def new_campaign(request):
    if request.method == 'POST':
        form = CampaignForm(request.POST)
        if form.is_valid():
            form.save()
            w = Workflow(campaign=form.instance)
            w.first_date = datetime.now() - timedelta(days=1)
            w.save()
            return redirect('tracker:choose_template', campaign_id=form.instance.id)
    else:
        form = CampaignForm()

    context = {
        'class_name': 'Kampagne',
        'form': form,
        'client_form': ClientForm(),
        'new': True
    }
    return render(request, 'main/edit_campaign.html', context)

def get_folder_name(path):
    elements = path.split('/')
    index = elements.index(settings.MEDIA_ROOT.replace('/', ''))
    return elements[index + 1]
    
def edit_campaign(request, campaign_id):
    campaign = Campaign.objects.get(id=campaign_id)
    if request.method == 'POST':
        action = request.POST.get('action', None)
        if action == 'SAVE_CAMPAIGN':
            form = CampaignForm(request.POST, instance=campaign)

            if form.is_valid():
                form.save()
                return redirect('main:edit_campaign', campaign_id=campaign_id)
        elif action == 'START_CAMPAIGN':
            campaign.start_date = datetime.now()
            campaign.status = Campaign.Status.ACTIVE
            campaign.save()
            messages.success(request, "Die Kampagne wurde erfolgreich gestartet")
            return redirect('main:edit_campaign', campaign_id=campaign_id)
        elif action == 'END_CAMPAIGN':
            campaign.end_date = datetime.now()
            campaign.status = Campaign.Status.FINISHED
            campaign.save()
            messages.success(request, "Die Kampagne wurde erfolgreich beendet")
            return redirect('main:edit_campaign', campaign_id=campaign_id)
    else:
        form = CampaignForm(instance=campaign)

    files = campaign.get_files()

    folders = {}
    for file in files:
        folder_name = get_folder_name(file.path)
        if folder_name in folders:
            folders[folder_name].append(file)
        else:
            folders[folder_name] = [file]

    context = {
        'campaign': campaign,
        'form': form,
        'folders': folders,
        'client_form': ClientForm()
    }
    return render(request, 'main/edit_campaign.html', context)

def clients(request):
    clients = Client.objects.all()
    clients_with_campaigns = []
    clients_without_campaigns = []
    
    for client in clients:
        if len(client.relevant_campaigns()) != 0:
            clients_with_campaigns.append(client)
        else:
            clients_without_campaigns.append(client)
    

    context = {
        'clients': sorted(clients_with_campaigns, key=lambda x: x.name) + sorted(clients_without_campaigns, key=lambda x: x.name)
    }
    return render(request, 'main/clients.html', context)

def new_client(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:clients')
    else:
        form = ClientForm()

    context = {
        'class_name': "Kunde",
        'form': form,
        'new': True,
        'url': reverse('main:new_client')
    }
    return render(request, 'main/simple_form.html', context)

def edit_client(request, client_id):
    client = Client.objects.get(id=client_id)
    if request.method == 'POST':
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            return redirect('main:clients')
    else:
        form = ClientForm(instance=client)
    
    context = {
        'class_name': 'Kunde',
        'form': form,
        'new': False,
        'url': reverse('main:edit_client', kwargs={'client_id': client_id})
    }
    return render(request, 'main/simple_form.html', context)

def post_handler(request):
    if request.method == 'GET':
        raise TypeError("This View should never be accessed by a GET request")

    action = request.POST['action']
    if action == 'LOGOUT':
        logout(request)
        return redirect('users:login')
    if action == 'HOME':
        m = Module(request.session['active_module'])
        return redirect(m.home_view)
    if action == 'TO_INDEX':
        return redirect('main:index')


# BACKGROUND
def bg_new_client(request):
    if request.method == "GET":
        raise ValueError("This view should never be accessed via GET")
    form = ClientForm(request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({"html": "", 'option': f"<option value='{form.instance.id}'>{form.instance.name}</option>"})
    return JsonResponse({
        'html': form.as_table(),
        'option': {}
    })

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}TITLE{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    <script type="text/javascript">
      const OVERVIEW_URL = "{% url 'tracker:overview' %}";
    </script>
    <script type="text/javascript" src="{% static 'main/js/base.js' %}"></script>
    {% block head %}{% endblock%}
  </head>
  <body>
    <div id="base_header">
      {% if ACTIVE_MODULE is not None %}
        <a href="{% url ACTIVE_MODULE.home_view %}"><img src="{% static 'main/images/house.png' %}" id="house"></a>
      {% endif %}
      <a href="{% url 'main:index' %}"><img src="{% static 'main/images/campagion_logo.png'%}" id="logo"></a>
      <img src="{% static 'main/images/exit_icon.png' %}" id="exit">
    </div>
    <div id="base_main_container">
        {% block content %}

        {% endblock %}
    </div>
    <div hidden>
      {% block forms %}

      {% endblock %}
      <form action="{% url 'main:post_handler' %}" method="POST" id="base_form" hidden>
        {% csrf_token %}
        <input type="text" name="action" id="base_input_action">
      </form>
    </div>

    {% if 'popup_title' in FILLED_BLOCKS or 'popup_content' in FILLED_BLOCKS %}
    <div id="popup_background" style="display: none;">
      <div id="popup_window">
        <div id="popup_title">{% block popup_title %}Test-Title{% endblock %}</div>
        <div id="popup_closer" class="noselect">X</div>
        <div id="popup_content">{% block popup_content %}Test-Content{% endblock %}</div>
      </div>
    </div>
    {% endif %}

    {% if messages %}
    <div id="message_container">
      {% for message in messages %}
        <div class="message{% if message.tags %} {{ message.tags }}{% endif %}">
          {{ message }}
        </div>
      {% endfor %}
    </div>
    {% endif %}
  </body>
</html>

main/templates/main/campaign.html
{% extends 'main/base.html' %}

{% block title %}Kampagne erstellen {% endblock %}

{% block head %}
<style media="screen">
  table {
    margin: 0px auto;
    margin-top: 40px;
  }
  table label {
    font-weight: normal;
  }
  table th {
    text-align: right;
  }
  .title {
    text-align: center;
    height: 40px;
    font-size: 30px;
    line-height: 30px;
    margin: 20px;
  }
</style>
{% endblock %}

{% block content %}
<div class="title">
  Neue Kampagne
</div>
<form action="{% if new %}{% url 'main:new_campaign' client.id %}{% else %}{% url 'main:edit_campaign'%}{% endif %}" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <div style="text-align: center; margin: 10px;">
    <input type="submit">
  </div>
</form>
{% endblock %}

main/templates/main/clients.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Kundenzone{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/clients.css' %}">
    <script>
        function new_client() {
            document.getElementById('new_client_form').submit();
        }
        function perform_search(value) {
            const clients = document.getElementsByClassName('client');

            for (let client of clients) {
                const name = client.dataset.name.toLowerCase();
                if (name.includes(value.toLowerCase())) {
                    client.style.display = "";
                } else {
                    client.style.display = "none";
                }
            }
        }
    </script>
{% endblock %}

{% block content %}
    <div id="main_container">
        <div class="title" style="grid-area: title;">
            Kundenzone
        </div>
        <div id="search_bar">
            <div id="search_wrapper">
                <label for="search_input">Suche:</label>
                <input type="text" id="search_input" onkeyup="perform_search(this.value)">
            </div>
        </div>
        <img src="{% static 'tracker/images/new_icon.png' %}" id="add_client" onclick="new_client()" width="32px">
        <div id="client_container">
            {% for client in clients %}
                <div class="client" data-name="{{ client.name }}">
                    <div class="name">{{ client.name }}</div>
                    <div class="data">{{ client.contact_name|default:"" }}</div>
                    <div class="data">{{ client.phone|default:"" }}</div>
                    <div class="data">{{ client.email|default:"" }}</div>
                    {% if client.relevant_campaigns|length != 0 %}
                        <div class="subtitle">Kampagnen</div>
                        <div class="sep"></div>
                    {% endif %}
                    
                    {% for campaign in client.relevant_campaigns %}
                    <a href="{% url 'main:edit_campaign' campaign.id %}"><div class="campaign">{{ campaign.name }}</div></a>
                    {% endfor %}
                    <div class="edit">
                        <a href="{% url 'main:edit_client' client.id %}">
                            <img src="{% static 'tracker/images/settings_icon.png' %}" width="35px" height="35px">
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block forms %}
    <form action="{% url 'main:new_client' %}" id="new_client_form"></form>
{% endblock %}

main/templates/main/edit_campaign.html
{% extends 'main/base.html' %}
{% load static %}
{% load filename %}

{% block title %}Kampagne bearbeiten{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/edit_campaign.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
    <script>
        const DELETE_ICON_PATH = "{% static 'tracker/images/delete_icon.png' %}";
        const API_URLS = {
            'sum': "{% url 'main:api_sum' %}",
            'sum_minicampaign': "{% url 'main:api_sum_mini' %}",
            'stats': "{% url 'main:api_data' %}",
            'stats_minicampaign': "{% url 'main:api_data_mini' %}",
            'minicampaigns': "{% url 'main:api_get_minicampaigns' %}"
        };
        const CAMPAIGN_ID = {{ campaign.id }};
    </script>
    <script src="{% static 'main/js/api_manager.js' %}"></script>
    <script src="{% static 'main/js/edit_campaign.js' %}"></script>
    <script src="{% static 'main/js/calendar.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="main_container">
        <div id="sidebar">
            <div class="sidebar_menu noselect selected" onclick="change_view(this);" data-tag="grunddaten">
                Grunddaten
            </div>
            <div class="sidebar_menu noselect" onclick="change_view(this);" data-tag="children">
                Werbelinien
            </div>
            {% if not new %}
                <div class="sidebar_menu noselect" onclick="change_view(this);" data-tag="api">
                    API-Daten
                </div>
                <div class="sidebar_menu noselect" onclick="change_view(this);" data-tag="files">
                    Dateien und Dokumente
                </div>
            {% endif %}
            <div class="sidebar_menu noselect" onclick="change_view(this);" data-tag="progress">
                Fortschritt
            </div>
        </div>
        <div id="content_container">
            <div id="grunddaten_container" class="view_container" style="display: block;">
                <div class="title">Grunddaten</div>
                <div class="form_container">
                    <form action="{% if not new %}{% url 'main:edit_campaign' campaign.id %}{% else %}{% url 'main:new_campaign' %}{% endif %}" method="POST" id="grunddaten_form">
                        {{ form.render|safe }}
                        <input type="text" name="action" value="SAVE_CAMPAIGN" hidden>
                        {% csrf_token %}
                    </form>
                </div>
                <div id="button_container">
                    <div class="button" onclick="submit_grunddaten()">Speichern</div>
                </div>
            </div>
            <div id="children_container" class="view_container" style="display: none;">
                <div class="title">
                    Werbelinien
                </div>
                <img id="new_minicampaign" src="{% static 'tracker/images/new_icon.png' %}">
                <div id="children_table_container">
                    <table id="children_table">
                        <colgroup>
                            <col style="width: 46%;">
                            <col style="width: 46%;">
                            <col style="width: 8%;">
                        </colgroup>
                        <tr>
                            <th>Name</th>
                            <th>API-ID</th>
                            <th></th>
                        </tr>
                        {% for child in campaign.children_set.all %}
                            <tr data-child_id="{{ child.id }}">
                                <td><input type="text" value="{{ child.name }}"></td>
                                <td><input type="text" value="{{ child.api_id }}"></td>
                                <td><img src="{% static 'tracker/images/delete_icon.png' %}" onclick="delete_row(this);"></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="button" id="save_children_button" onclick="save_children()">
                    Speichern
                </div>
            </div>
            <div id="api_container" class="view_container" style="display: none;">
                <div class="title">API-Daten</div>
                <div class="form_container" id="api_form_container">
                    {% if not campaign.is_pre_active %}
                        <div id="minicampaign_changer">
                            <img src="{% static 'main/images/arrow.png' %}" style="grid-column: 1; transform: rotate(180deg); display: none;" id="left_arrow">
                            <div class="minicampaign_name" id="minicampaign_left_name" style="grid-column: 2; display: none;">Name links</div>
                            <div id="minicampaign_title" style="grid-column: 3;">
                                Gesamt
                            </div>
                            <div class="minicampaign_name" id="minicampaign_right_name" style="grid-column: 4; text-align: right; display: none;" id="right_arrow_div">Name rechts</div>
                            <img src="{% static 'main/images/arrow.png' %}" style="grid-column: 5; display: none;" id="right_arrow">
                        </div>
                        <table id="api_table">
                        </table>
                        <div style="text-align: center;">
                            <span>Startdatum:</span>
                            <carbox-picker id="startdate_picker" value="{{ campaign.start_date|date:"j/n/Y" }}"></carbox-picker>
                        </div>
                        <div style="text-align: center;">
                            <span>Enddatum:</span>
                            <carbox-picker id="enddate_picker" value="{% if campaign.end_date is None %}{% now "j/n/Y" %}{% else %}{{ campaign.end_date|date:"j/n/Y" }}{% endif %}"></carbox-picker>
                        </div>
                        <div id="graph_container">
                            <canvas id="api_graph"></canvas>
                        </div>
                        <div id="reset_days" data-start_date="{{ campaign.start_date|date:"j/n/Y" }}" data-end_date="{% if campaign.end_date is None %}{% now "j/n/Y" %}{% else %}{{ campaign.end_date|date:"j/n/Y" }}{% endif %}">
                            Zeitraum zurücksetzen
                        </div>
                    {% else %}
                        <p>Zu dieser Kampagne wurden noch keine API-Daten gefunden</p>
                    {% endif %}
                </div>
            </div>
            <div id="files_container" class="view_container" style="display: none;">
                <div id="folder_sidemenu">
                    {% for folder in folders.keys %}
                        <div class="folder noselect" onclick="open_folder(this)" data-folder="{{ folder }}">
                            {{ folder }}
                        </div>
                    {% endfor %}
                </div>
                <div id="files_sidemenu">

                </div>
                <div id="iframe_container">
                    <iframe src="" frameborder="0" id="file_iframe">

                    </iframe>
                </div>
            </div>
            <div id="progress_container" class="view_container" style="display: none;">
                <div class="title">Fortschritt</div>
                <div class="progress" style="{% if campaign.id is not None %}background-color: #32cf4e{% endif %}">Kampagne erstellt</div>
                <div class="progress" style="{% if campaign.workflow.is_started %}background-color: #32cf4e{% endif %}">Workflow gestartet</div>
                <div class="progress" style="{% if campaign.workflow.is_finished %}background-color: #32cf4e{% endif %}">Workflow abgeschlossen</div>
                <div class="progress" style="{% if campaign.is_started %}background-color: #32cf4e{% endif %}">Kampagne gestartet</div>
                <div class="progress" style="{% if campaign.has_ended %}background-color: #32cf4e{% endif %}">Kampagne beendet</div>
                <div id="button_container">
                    {% if campaign.workflow.is_finished %}
                        {% if not campaign.is_started %}
                            <div class="button" onclick="post('START_CAMPAIGN');">
                                Kampagne starten
                            </div>
                        {% elif not campaign.has_ended %}
                            <div class="button" onclick="post('END_CAMPAIGN');">
                                Kampagne beenden
                            </div>
                        {% endif %}
                    {% elif campaign.workflow.is_active %}
                        <a href="{% url 'tracker:workflow' campaign.id %}">
                            <div class="button">
                                Workflow öffnen
                            </div>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div id="hidden_div" hidden>
            {% for folder, files in folders.items %}
                {% for file in files %}
                    <div class="file noselect" data-folder="{{ folder }}" data-url="{{ file.url }}" onclick="show_file(this)">
                        {{ file|filename }}
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block forms %}
    {% if not new %}
        <form action="{% url 'main:edit_campaign' campaign.id %}" method="POST" id="button_form">
            {% csrf_token %}
            <input type="text" name="action" id="input_action">
        </form>
    {% endif %}
{% endblock %}

{% block popup_title %}Kunde erstellen{% endblock %}
{% block popup_content %}
    <form action="{% url 'main:bg_new_client' %}" id="new_client_form" method="POST">
        <table id="new_client_table">
            {{ client_form.as_table }}
        </table>
        {% csrf_token %}
    </form>
    <div class="button" onclick="submit_client_form()">
        Speichern
    </div>
{% endblock %}

main/templates/main/edit_client.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}{{ client.name }}{% endblock%}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/edit_client.css' %}">
{% endblock %}

{% block content %}
<div id="main_container">

    
</div>
{% endblock %}